/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type Language = 'en' | 'bn';

export const translations = {
  en: {
    // Header & Bottom Bar
    home: 'Home',
    sports: 'Sports',
    games: 'Games',
    promotions: 'Promos',
    profile: 'Profile',
    admin: 'Admin',
    wallet: 'Wallet',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    balance: 'Balance',
    vipLevel: 'VIP Level',
    notifications: 'Notifications',
    support: 'Support',
    leaderboard: 'Leaderboard',
    news: 'Latest News',
    
    // Auth
    username: 'Username',
    password: 'Password',
    email: 'Email Address',
    phone: 'Phone Number',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    referralCodeOpt: 'Referral Code (Optional)',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    
    // Sportsbook
    liveMatches: 'Live Matches',
    upcomingMatches: 'Upcoming Matches',
    placedPredictions: 'My Bets',
    betSlip: 'Bet Slip',
    stakeAmount: 'Stake Amount',
    potentialPayout: 'Est. Payout',
    placeBet: 'Confirm Bet',
    selectOdd: 'Select Odds to place prediction',
    homeWin: '1 (Home)',
    draw: 'X (Draw)',
    awayWin: '2 (Away)',
    noMatches: 'No matches found.',
    searchLeague: 'Search league or team...',
    
    // Dashboard & Wallet
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    history: 'History',
    referral: 'Refer & Earn',
    vipClub: 'VIP Club',
    supportDesk: 'Help Support',
    bkashDeposit: 'bKash Wallet',
    nagadDeposit: 'Nagad Wallet',
    rocketDeposit: 'Rocket Wallet',
    depositInstructions: 'Send money to our agent number, then paste the Transaction ID (TrxID) below to credit your account:',
    copyNumber: 'Copy Number',
    trxIdPlaceholder: 'Enter TrxID / Transaction Reference',
    submitDeposit: 'Submit Deposit Request',
    minDepositLimit: 'Min deposit limit:',
    minWithdrawLimit: 'Min withdraw limit:',
    recipientNumber: 'Recipient Phone Number',
    withdrawInstructions: 'Funds will be securely processed and transferred to your mobile wallet within 2-4 hours.',
    submitWithdraw: 'Request Withdrawal',
    vipProgress: 'VIP Club Progress',
    nextLevelPoints: 'points to next VIP rank',
    referralLink: 'Your Referral Link',
    copyLink: 'Copy Code',
    referralEarnings: 'Total Referral Earnings',
    createTicket: 'Open Support Ticket',
    ticketSubject: 'Subject / Issue Heading',
    ticketMessage: 'Explain your issue in detail...',
    submitTicket: 'Submit Ticket',
    
    // Demo Games
    demoNotice: 'DEMO GAMEPLAY - NO REAL MONEY WAGERING',
    crashGame: 'Aviator Crash',
    luckySpin: 'Lucky Spin Wheel',
    diceGame: 'Over/Under Dice',
    rouletteGame: 'Premium Roulette',
    slotsGame: 'Classic Slots',
    bet: 'Place Bet',
    cashout: 'CASHOUT',
    multiplier: 'Multiplier',
    crashed: 'CRASHED at',
    chooseColor: 'Pick Color',
    spin: 'SPIN NOW',
    rolling: 'Rolling...',
    jackpot: 'JACKPOT!',
    
    // Footer & Static Pages
    aboutText: 'BETEPRO is the leading sports gaming and match-prediction simulation platform. Practice and test your strategies on live football, cricket, and casino mechanics completely risk-free.',
    faq: 'Frequently Asked Questions',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    aboutUs: 'About Us',
    contactUs: 'Contact support',
    rightsReserved: 'All rights reserved.'
  },
  bn: {
    // Header & Bottom Bar
    home: 'হোম',
    sports: 'স্পোর্টস',
    games: 'গেমস',
    promotions: 'অফার',
    profile: 'প্রোফাইল',
    admin: 'অ্যাডমিন',
    wallet: 'ওয়ালেট',
    login: 'লগইন',
    register: 'নিবন্ধন',
    logout: 'লগআউট',
    balance: 'ব্যালেন্স',
    vipLevel: 'ভিআইপি লেভেল',
    notifications: 'নোটিফিকেশন',
    support: 'সাপোর্ট',
    leaderboard: 'লিডারবোর্ড',
    news: 'তাজা খবর',
    
    // Auth
    username: 'ইউজারনেম',
    password: 'পাসওয়ার্ড',
    email: 'ইমেইল অ্যাড্রেস',
    phone: 'মোবাইল নাম্বার',
    fullName: 'পূর্ণ নাম',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    referralCodeOpt: 'রেফার কোড (ঐচ্ছিক)',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    dontHaveAccount: 'অ্যাকাউন্ট নেই? নতুন খুলুন',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    
    // Sportsbook
    liveMatches: 'চলতি ম্যাচ সমূহ',
    upcomingMatches: 'আসন্ন ম্যাচ সমূহ',
    placedPredictions: 'আমার বাজি',
    betSlip: 'বেট স্লিপ',
    stakeAmount: 'বাজির পরিমাণ',
    potentialPayout: 'সম্ভাব্য লাভ',
    placeBet: 'বেট কনফার্ম করুন',
    selectOdd: 'বাজি ধরতে অডস সিলেক্ট করুন',
    homeWin: '১ (হোম দল)',
    draw: 'X (ড্র)',
    awayWin: '২ (অ্যাওয়ে দল)',
    noMatches: 'কোন ম্যাচ পাওয়া যায়নি।',
    searchLeague: 'লীগ বা দলের নাম খুঁজুন...',
    
    // Dashboard & Wallet
    deposit: 'ডিপোজিট',
    withdraw: 'উইথড্র',
    history: 'লেনদেন ট্র্যাকার',
    referral: 'রেফার করুন',
    vipClub: 'ভিআইপি ক্লাব',
    supportDesk: 'সহায়তা ডেস্ক',
    bkashDeposit: 'বিকাশ ওয়ালেট',
    nagadDeposit: 'নগদ ওয়ালেট',
    rocketDeposit: 'রকেট ওয়ালেট',
    depositInstructions: 'আমাদের এজেন্ট নাম্বারে টাকা পাঠিয়ে নিচে ট্রানজেকশন আইডি (TrxID) দিন। অ্যাডমিন যাচাই করে ব্যালেন্স যুক্ত করবে:',
    copyNumber: 'নাম্বার কপি করুন',
    trxIdPlaceholder: 'ট্রানজেকশন আইডি (TrxID) লিখুন',
    submitDeposit: 'ডিপোজিট সাবমিট করুন',
    minDepositLimit: 'সর্বনিম্ন ডিপোজিট:',
    minWithdrawLimit: 'সর্বনিম্ন উইথড্র:',
    recipientNumber: 'টাকা পাওয়ার মোবাইল নাম্বার',
    withdrawInstructions: '২ থেকে ৪ ঘণ্টার মধ্যে আপনার মোবাইল ওয়ালেটে টাকা পৌঁছে যাবে।',
    submitWithdraw: 'উইথড্র রিকোয়েস্ট করুন',
    vipProgress: 'ভিআইপি ক্লাব অগ্রগতি',
    nextLevelPoints: 'পয়েন্ট পরবর্তী লেভেলের জন্য',
    referralLink: 'আপনার রেফারেল কোড',
    copyLink: 'কোড কপি করুন',
    referralEarnings: 'মোট রেফারেল আয়',
    createTicket: 'নতুন সাপোর্ট টিকেট',
    ticketSubject: 'টিকেট বিষয়',
    ticketMessage: 'আপনার সমস্যাটি বিস্তারিত লিখুন...',
    submitTicket: 'টিকেট সাবমিট করুন',
    
    // Demo Games
    demoNotice: 'ডেমো গেমপ্লে - কোন আসল টাকা লেনদেন হয় না',
    crashGame: 'অ্যাভিয়েটর ক্র্যাশ',
    luckySpin: 'ভাগ্য চাকা স্পিন',
    diceGame: 'ডাইস রোল খেলা',
    rouletteGame: 'প্রিমিয়াম রুলেট',
    slotsGame: 'ক্লাসিক স্লটস',
    bet: 'বাজি ধরুন',
    cashout: 'ক্যাশ আউট',
    multiplier: 'মাল্টিপ্লায়ার',
    crashed: 'ক্র্যাশ হয়েছে',
    chooseColor: 'রঙ নির্বাচন করুন',
    spin: 'স্পিন করুন',
    rolling: 'ঘুরছে...',
    jackpot: 'জ্যাকপট!',
    
    // Footer & Static Pages
    aboutText: 'BETEPRO হলো আধুনিক স্পোর্টস ও ক্যাসিনো ডেমো গেম সিমুলেশন প্ল্যাটফর্ম। ফুটবল, ক্রিকেট ও নানা আকর্ষণীয় খেলায় কোনো আর্থিক ঝুঁকি ছাড়াই অনুশীলন করুন।',
    faq: 'সাধারণ জিজ্ঞাসা সমূহ',
    terms: 'ব্যবহারের নিয়মাবলী',
    privacy: 'গোপনীয়তা নীতি',
    aboutUs: 'আমাদের সম্পর্কে',
    contactUs: 'সহায়তা নিন',
    rightsReserved: 'সর্বস্বত্ব সংরক্ষিত।'
  }
};
